
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADDRESSNAME COMMA COMMENTS FUNCTIONNAME NUMBER OPCODE REGISTER SEMICOLONcommand : ADDRESSNAME OPCODE NUMBER SEMICOLON\n\t\t\t\t| OPCODE NUMBER SEMICOLON\n\t\t\t\t| OPCODE body\n\t\t\t\t| OPCODEbody : REGISTER COMMA REGISTER COMMA REGISTER SEMICOLON\n\t\t\t| REGISTER COMMA REGISTER NUMBER SEMICOLON\n\t\t\t| REGISTER COMMA NUMBER SEMICOLON\n\t\t\t| REGISTER COMMA REGISTER SEMICOLON\n\t\t\t| REGISTER SEMICOLON'
    
_lr_action_items = {'ADDRESSNAME':([0,],[2,]),'OPCODE':([0,2,],[3,4,]),'$end':([1,3,6,9,11,12,16,18,20,21,],[0,-4,-3,-2,-9,-1,-8,-7,-6,-5,]),'NUMBER':([3,4,10,13,],[5,8,14,17,]),'REGISTER':([3,10,15,],[7,13,19,]),'SEMICOLON':([5,7,8,13,14,17,19,],[9,11,12,16,18,20,21,]),'COMMA':([7,13,],[10,15,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'command':([0,],[1,]),'body':([3,],[6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> command","S'",1,None,None,None),
  ('command -> ADDRESSNAME OPCODE NUMBER SEMICOLON','command',4,'p_command','ArmYacc.py',12),
  ('command -> OPCODE NUMBER SEMICOLON','command',3,'p_command','ArmYacc.py',13),
  ('command -> OPCODE body','command',2,'p_command','ArmYacc.py',14),
  ('command -> OPCODE','command',1,'p_command','ArmYacc.py',15),
  ('body -> REGISTER COMMA REGISTER COMMA REGISTER SEMICOLON','body',6,'p_body','ArmYacc.py',27),
  ('body -> REGISTER COMMA REGISTER NUMBER SEMICOLON','body',5,'p_body','ArmYacc.py',28),
  ('body -> REGISTER COMMA NUMBER SEMICOLON','body',4,'p_body','ArmYacc.py',29),
  ('body -> REGISTER COMMA REGISTER SEMICOLON','body',4,'p_body','ArmYacc.py',30),
  ('body -> REGISTER SEMICOLON','body',2,'p_body','ArmYacc.py',31),
]
